// Validates the C++ engine against reference cases produced by the Python
// oracle (python/reference/coulomb.py). The fixtures are generated by
// tests/reference/gen_reference_cases.py and checked into the repo as JSON, so
// these tests run in CI without any Python.
//
// Tier 1 (here): force kernel + potential energy at the initial configuration.
// These are exact comparisons (no time integration involved).
// Tier 2 (asymptotic momenta) is added once the RK45 integrator is ported.

#include <fstream>
#include <string>
#include <vector>

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
#include <nlohmann/json.hpp>

#include "coulomb/molecule.hpp"
#include "coulomb/system.hpp"

using namespace coulomb;
using Catch::Matchers::WithinAbs;
using Catch::Matchers::WithinRel;
using json = nlohmann::json;

namespace {

Vec3 to_vec3(const json& a) {
  return Vec3{a.at(0).get<Real>(), a.at(1).get<Real>(), a.at(2).get<Real>()};
}

json load_reference() {
  std::ifstream in(COULOMB_REFERENCE_JSON);
  REQUIRE(in.good());  // fixture must exist; regenerate if this fails
  json doc;
  in >> doc;
  return doc;
}

struct Case {
  std::string name;
  Molecule molecule;
  State state;
  std::vector<Vec3> forces_init;
  Real potential_energy_init{};
};

Case parse_case(const json& c) {
  Case out;
  out.name = c.at("name").get<std::string>();

  const auto& symbols = c.at("symbols");
  const auto& masses = c.at("masses");
  const auto& charges = c.at("charges");
  for (std::size_t i = 0; i < symbols.size(); ++i) {
    out.molecule.atoms.push_back(
        {symbols.at(i).get<std::string>(), masses.at(i).get<Real>(), charges.at(i).get<Real>()});
  }

  for (const auto& p : c.at("positions_init")) out.state.positions.push_back(to_vec3(p));

  // The engine's State carries velocity; the contract stores momentum. Convert
  // v = p / m. Momenta are zero today but this stays correct if that changes.
  const auto& momenta = c.at("momenta_init");
  for (std::size_t i = 0; i < momenta.size(); ++i) {
    out.state.velocities.push_back(to_vec3(momenta.at(i)) * (Real{1} / out.molecule.atoms[i].mass));
  }
  for (const auto& f : c.at("forces_init")) out.forces_init.push_back(to_vec3(f));
  out.potential_energy_init = c.at("potential_energy_init").get<Real>();
  return out;
}

}  // namespace

TEST_CASE("force kernel matches the Python oracle", "[reference][force]") {
  const json doc = load_reference();
  REQUIRE(doc.at("coulomb_constant").get<Real>() == 1.0);
  CoulombForce force(1.0);

  for (const auto& jc : doc.at("cases")) {
    Case c = parse_case(jc);
    DYNAMIC_SECTION(c.name) {
      std::vector<Vec3> acc;
      force.accelerations(c.molecule, c.state, acc);
      REQUIRE(acc.size() == c.forces_init.size());

      for (std::size_t i = 0; i < acc.size(); ++i) {
        // Engine returns acceleration; recover force as F = m * a.
        const Real m = c.molecule.atoms[i].mass;
        REQUIRE_THAT(acc[i].x * m, WithinAbs(c.forces_init[i].x, 1e-9));
        REQUIRE_THAT(acc[i].y * m, WithinAbs(c.forces_init[i].y, 1e-9));
        REQUIRE_THAT(acc[i].z * m, WithinAbs(c.forces_init[i].z, 1e-9));
      }
    }
  }
}

TEST_CASE("potential energy matches the Python oracle", "[reference][energy]") {
  const json doc = load_reference();
  CoulombForce force(1.0);

  for (const auto& jc : doc.at("cases")) {
    Case c = parse_case(jc);
    DYNAMIC_SECTION(c.name) {
      REQUIRE_THAT(force.potential_energy(c.molecule, c.state),
                   WithinRel(c.potential_energy_init, 1e-12));
    }
  }
}
