// Validates the C++ engine against reference cases produced by the Python
// oracle (python/reference/coulomb.py). The fixtures are generated by
// tests/reference/gen_reference_cases.py and checked into the repo as JSON, so
// these tests run in CI without any Python.
//
// Tier 1: force kernel + potential energy at the initial configuration. These
// are exact comparisons (no time integration involved).
// Tier 2: asymptotic momenta after integrating the explosion to convergence
// with the adaptive RK45 (see the dedicated test below).

#include <algorithm>
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
#include <cmath>
#include <fstream>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

#include "coulomb/driver.hpp"
#include "coulomb/integrator.hpp"
#include "coulomb/molecule.hpp"
#include "coulomb/system.hpp"

using namespace coulomb;
using Catch::Matchers::WithinAbs;
using Catch::Matchers::WithinRel;
using json = nlohmann::json;

namespace {

Vec3 to_vec3(const json& a) {
  return Vec3{a.at(0).get<Real>(), a.at(1).get<Real>(), a.at(2).get<Real>()};
}

json load_reference() {
  std::ifstream in(COULOMB_REFERENCE_JSON);
  REQUIRE(in.good());  // fixture must exist; regenerate if this fails
  json doc;
  in >> doc;
  return doc;
}

struct Case {
  std::string name;
  Molecule molecule;
  State state;
  std::vector<Vec3> forces_init;
  Real potential_energy_init{};
  std::vector<Vec3> momenta_final;
  Real kinetic_energy_final{};
};

Case parse_case(const json& c) {
  Case out;
  out.name = c.at("name").get<std::string>();

  const auto& symbols = c.at("symbols");
  const auto& masses = c.at("masses");
  const auto& charges = c.at("charges");
  for (std::size_t i = 0; i < symbols.size(); ++i) {
    out.molecule.atoms.push_back(
        {symbols.at(i).get<std::string>(), masses.at(i).get<Real>(), charges.at(i).get<Real>()});
  }

  for (const auto& p : c.at("positions_init")) out.state.positions.push_back(to_vec3(p));

  // The engine's State carries velocity; the contract stores momentum. Convert
  // v = p / m. Momenta are zero today but this stays correct if that changes.
  const auto& momenta = c.at("momenta_init");
  for (std::size_t i = 0; i < momenta.size(); ++i) {
    out.state.velocities.push_back(to_vec3(momenta.at(i)) * (Real{1} / out.molecule.atoms[i].mass));
  }
  for (const auto& f : c.at("forces_init")) out.forces_init.push_back(to_vec3(f));
  out.potential_energy_init = c.at("potential_energy_init").get<Real>();
  for (const auto& p : c.at("momenta_final")) out.momenta_final.push_back(to_vec3(p));
  out.kinetic_energy_final = c.at("kinetic_energy_final").get<Real>();
  return out;
}

}  // namespace

TEST_CASE("force kernel matches the Python oracle", "[reference][force]") {
  const json doc = load_reference();
  REQUIRE(doc.at("coulomb_constant").get<Real>() == 1.0);
  CoulombForce force(1.0);

  for (const auto& jc : doc.at("cases")) {
    Case c = parse_case(jc);
    DYNAMIC_SECTION(c.name) {
      std::vector<Vec3> acc;
      force.accelerations(c.molecule, c.state, acc);
      REQUIRE(acc.size() == c.forces_init.size());

      for (std::size_t i = 0; i < acc.size(); ++i) {
        // Engine returns acceleration; recover force as F = m * a.
        const Real m = c.molecule.atoms[i].mass;
        REQUIRE_THAT(acc[i].x * m, WithinAbs(c.forces_init[i].x, 1e-9));
        REQUIRE_THAT(acc[i].y * m, WithinAbs(c.forces_init[i].y, 1e-9));
        REQUIRE_THAT(acc[i].z * m, WithinAbs(c.forces_init[i].z, 1e-9));
      }
    }
  }
}

// Tier 2: asymptotic momenta. Integrate each case to the explosion's
// large-time limit with the adaptive RK45 and compare the final per-atom
// momenta against the Python oracle (scipy solve_ivp out to t = 1e10).
//
// Two engine-by-design differences from the oracle keep this from being an
// exact match: (a) we terminate on a potential-energy threshold rather than a
// hard-coded t = 1e10, and (b) the redistribution step pins the final kinetic
// energy to E_0 exactly, whereas scipy's non-symplectic RK45 lets the energy
// drift by ~rtol. At the threshold used here the residual is dominated by (b):
// it floors near 2.4e-8 for two_protons, which is exactly scipy's measured
// energy drift sqrt(KE_final/PE_0) - 1 -- i.e. our momenta are the more
// energy-faithful ones and the gap is the oracle's own integration error. The
// 1e-6 tolerance sits comfortably above that floor.
TEST_CASE("asymptotic momenta match the Python oracle", "[reference][rk45]") {
  const json doc = load_reference();
  CoulombForce force(doc.at("coulomb_constant").get<Real>());

  IntegratorOptions opts{doc.at("rk_rtol").get<Real>(), doc.at("rk_atol").get<Real>()};
  RunConfig cfg;
  cfg.pe_stop_fraction = 1e-10;
  cfg.redistribute_energy = true;

  for (const auto& jc : doc.at("cases")) {
    Case c = parse_case(jc);
    DYNAMIC_SECTION(c.name) {
      auto integ = make_integrator(IntegratorKind::RK45, opts);
      const RunResult run = run_to_convergence(c.molecule, force, *integ, c.state, cfg);
      REQUIRE(run.converged);

      // Largest momentum magnitude in the case sets the absolute scale for
      // comparing the near-zero (symmetry) components.
      Real scale = 0;
      for (const auto& p : c.momenta_final) {
        scale = std::max({scale, std::abs(p.x), std::abs(p.y), std::abs(p.z)});
      }

      REQUIRE(c.state.size() == c.momenta_final.size());
      for (std::size_t i = 0; i < c.state.size(); ++i) {
        const Real m = c.molecule.atoms[i].mass;
        const Vec3 p{c.state.velocities[i].x * m, c.state.velocities[i].y * m,
                     c.state.velocities[i].z * m};
        const Vec3& ref = c.momenta_final[i];
        REQUIRE_THAT(p.x, WithinRel(ref.x, 1e-6) || WithinAbs(ref.x, scale * 1e-6));
        REQUIRE_THAT(p.y, WithinRel(ref.y, 1e-6) || WithinAbs(ref.y, scale * 1e-6));
        REQUIRE_THAT(p.z, WithinRel(ref.z, 1e-6) || WithinAbs(ref.z, scale * 1e-6));
      }
    }
  }
}

TEST_CASE("potential energy matches the Python oracle", "[reference][energy]") {
  const json doc = load_reference();
  CoulombForce force(1.0);

  for (const auto& jc : doc.at("cases")) {
    Case c = parse_case(jc);
    DYNAMIC_SECTION(c.name) {
      REQUIRE_THAT(force.potential_energy(c.molecule, c.state),
                   WithinRel(c.potential_energy_init, 1e-12));
    }
  }
}
